version: "3"

services:
  coupon-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS=true
      - SPRING_H2_CONSOLE_PATH=/h2-console
